---
- name: Find available data centers
  uri:
    url: '{{ consul_catalog_url }}/datacenters'
  register: data_centers

- name: Find available Geth API RPC services
  uri:
    url: '{{ consul_catalog_url }}/service/{{ geth_node_api_consul_name }}-rpc?dc={{ item }}'
  with_items: '{{ data_centers.json }}'
  register: geth_rpc_services

- name: Find available Geth API WebSocket services
  uri:
    url: '{{ consul_catalog_url }}/service/{{ geth_node_api_consul_name }}-ws?dc={{ item }}'
  with_items: '{{ data_centers.json }}'
  register: geth_ws_services
