---
# Communityu test REST API endpoint.
beacon_node_rest_address: '0.0.0.0'

# WARNING: This will change if number of nodes changes.
redirect_ports:
  # beacon-node-pyrmont-unstable-01
  - { src: 80, dst: 9301, comment: 'Test Beacon API (80->9301/tcp)' }

# Open Ports
open_ports_default_comment: 'Test Beacon API'
open_ports_list:
  - { port: 80 }

