---
# CloudFlare Origin certificates
origin_certs:
  - domain: 'status.im'
    crt: '{{lookup("passwordstore", "cloud/Cloudflare/status.im/origin.crt returnall=true")}}'
    key: '{{lookup("passwordstore", "cloud/Cloudflare/status.im/origin.key returnall=true")}}'
    default: true

# Consul Catalog Query URL
consul_catalog_url: 'http://localhost:8500/v1/catalog'

# Root password
bootstrap__root_pass: '{{lookup("passwordstore", "hosts/admin-pass")}}'
# TRACE needs more disk space
bootstrap__rsyslog_docker_logs_path: '/docker/log'
# The volume of logs is too big and Nimbus team doesn't use their own cluster
bootstrap__rsyslog_docker_logstash_send: false
# Print just the message, lower size of log files and make parsing easier
bootstrap__rsyslog_docker_format: !unsafe '%msg:2:2048%\n'
# lower local retention to save space
bootstrap__logrotate_frequency: 'hourly'
bootstrap__logrotate_count: 72
bootstrap__logrotate_mbytes: 500

# Consul Encryption
consul_encryption_key: '{{lookup("passwordstore", "services/consul/encryption-key")}}'

# Beacon nodes can be quite memory hungry
swap_file_path: '/docker/main.swap'
swap_file_size_mb: 2048

# Custom SSH accounts for Nimbus fleet
bootstrap__active_extra_users:
  - { name: dustin,  uid: 7016, groups: [], key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKrxMjWZZJ7E6EQY77IbOGaj1q6YzlRnQnCbTQqZja4c user@merfeint' }
  - { name: jacek,   uid: 7017, groups: [], key: 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAn/DafiXekTLUKznvRmdEBit5ZQ2DN+C25oom41ZMe8YvUe5y10dEpY5xHq37hMfE/B3LOVuCLOvWvV4wp8VIQHBmtI5olFQc7bNk+VyfHOSj7/e54vfkVHzbicUpMXaKLqxo7u9m5/lTE3JTKxbj6jIEIDMEUglXs8p9FGnKlJeEYBO7NDDfFa1NtrmJeQUQO7PCt4Ik8IAgqua07T1AEm9qADs6UPhjJ9zyr+QPo3Lk6qcQ/MFB4OQ8ZfiPGJ9Bx/doDSED5Ik3Y/yrb0vgWRR0Co5oVCAyx/jyNDxDtDSGE7TTMD3DGQyvnuBsvSm+vyrNuD3Sziy+aX4KNXRCTQ== arnetheduck@creator' }
  - { name: zahary,  uid: 7024, groups: [], key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZ4uk6O6e6KgiTGVOntGbUN+tUXM5XbnK4x9RPc8hsmphO0SIi/jim8TDh8SstyNA7IRx5TG3//tAzrjikA3xBfBktiZc7cIklkKwVsby7WEThbu99B+tKfXGrJEaIoXuGc7nk/t1ynMqbLSxo44Yu3+OksozDxtj1mDl2ze+ICa7XteAJgu7vIsfKUZwnpIVXglfqve0x/GJ8oQyp4vx7MFdaaBTl4yLyajwd+h+tINmf4fikUl34gVTLtM2VxXHy2VtbzjQUXb7pCISXELyXy0OnJ6HczNiWA2K0z47pohC5cAFYlErhmbZ1MRhKYysEAm/mAasTPRVKTK4agpSB zahary@status.im' }
  - { name: mamy,    uid: 7025, groups: [], key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCr/O5OUmeUaSzVTotWHBUCCkD+LhzT8HxmuuZ3bUiL6Cp0/1vrUZDlduNJjjIDdHs5mcFBGAPn3vRF31CnG0aoe29RXYAwEPBL3dYQ0zZv0n4RT/XUGirnpbv3LnURvpg7+2JuO+ebrK6LSmRG45YebyipzSimE6Q80isbbDUh6PXJEhiRAslvnkPskOF5qNnKcuZtCfiJ6UdlJ8YDPidEZ5NDW+NDfAWQyo9r7ZY3EsaKJ2honUx0CkxLti1WalG83zdWFOr3xrmEyJM69h4yigut2Xc0iuFmj915rFMS+gxcXG00DOVftqQ0kAf/eOVB/LlDUfs9r9mhod0y2wlX mamy@status.im' }
  - { name: stefan,  uid: 7029, groups: [], key: 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAw+3UpA5lT+8uAHdexl8isVhJX/I9knR34IRRkvEUaJzFF8XbTBeMsFHWTdY97zA9pl3GToKAymsw6+kBJ21yNztmRBQIpI1zmdhX6rV2u7waZUcOzyZDclOAG51TOijbzjWtDS/O0OGCEUsWDU8vvX10YGg0nHOjGI6uumUJYQp67C1Z5101Ygn3IhkBStzc7Pk2rUDErYFhom4KKD8w66vrPG9kqsR2i/pcW3EPI/5dz8FriaK+GB7OoZ7nTFhP/IlIV7hJUQZaOA69hkwwBz8LE6eTgoZwX6Q4b+ZxMXBR51xiljMYfKYg4FUGhcRdljxPr8HbObOf5YwTz5Vtaw== stefan@status.im' }
  - { name: dryajov, uid: 7030, groups: [], key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBjhsSxUXSQBv6PFEwE9TYG0TeuzabRipy/IoIS33BTt dryajov@status.im' }
  - { name: kim,     uid: 7031, groups: [], key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqPvYjYJjO0rCgeYsTp2kn0oyQLKHgvcjIYVeaQzjZ3VB5V+34AadjjYh8ULhuzTPl25gbVI0KAWbsui4im/04tBv9Bn8xAEvLcWwab5t7a8GZLGKXOl3bi6S7Vmal6e94mKht1wflS9hGu0o6q/fHanu/WPKhtc1zwg50Qlrs2/9DYP9Qqo0ekHnuzip1Trdmls33DZB1WehZx7/rNKwppE0aHUv7vgh7vc+FAU/RnyeHM2bJRfq/AxiAs+Fas5MrO+9Mm8jPA2Jm6TRDGmXg5DB+0+u+qZF15eJ+ujKXhgnVPJBkSuAryTPob7FA1Eovc9HBDhOQCKC0ialiJm+5 kim.demey@status.im' }
  - { name: giovanni,uid: 7032, groups: [], key: 'ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAGn4vdHz/zGgjtdcWZjmUwerVNezDo5g0i+a0rcHvUsHCdfJ1yN2inqvib+RxPwGYAzgKoT1J5y+SIaGO740XupgQCrTqqyWeaeU+k+GjQF8JGiAyG8htKkFawR/mZBsXvosp/D9rA2zr8ms8q8vJJV73w/hMKbBoJB8CLEvBqTkY+1Gg== giova@DESKTOP-7CNNO9E' }

# Nimbus ------------------------------
beacon_node_cont_name: 'beacon-node-{{ beacon_node_network }}-{{ beacon_node_cont_tag }}'
beacon_node_log_level: DEBUG
beacon_node_timer_rebuild: true

# ports
beacon_node_rpc_port: '11000'
beacon_node_metrics_port : '9300'
beacon_node_listening_port: '9100'
beacon_node_discovery_port: '9100'

# Infura URL
beacon_node_web3_url: '{{ lookup("passwordstore", "service/Nimbus/infura-url") }}'

# resource limits
beacon_node_mem_limit: '{{ (ansible_memtotal_mb * 0.60) | int }}'
beacon_node_mem_reserve: '{{ (ansible_memtotal_mb * 0.4) | int }}'

# Validators --------------------------
dist_validators_cont_name: '{{ beacon_node_cont_name }}'
dist_validators_name: '{{ beacon_node_network }}_deposits'
dist_validators_data_path: '{{ beacon_node_cont_vol }}/data/{{ beacon_node_data_folder }}'
