---
# Docker image builds
beacon_node_builds_docker_hub_user: '{{lookup("passwordstore", "cloud/DockerHub/user")}}'
beacon_node_builds_docker_hub_token: '{{lookup("passwordstore", "cloud/DockerHub/token")}}'

# The -t3a suffix is because of native compilation
beacon_node_builds_branches: []
  - name: 'devel-t3a'
    branch: 'devel'
    targets: ['nimbus_beacon_node', 'nimbus_signing_process']
    frequency: '*-*-* 10:00:00'
  - name: 'master-t3a'
    branch: 'master'
    targets: ['nimbus_beacon_node', 'nimbus_signing_process']
    frequency: '*-*-* 02:00:00'
  - name: 'libp2p-t3a'
    branch: 'nim-libp2p-auto-bump'
    targets: ['nimbus_beacon_node', 'nimbus_signing_process']
    frequency: '*-*-* 18:00:00'
  - name: 'toledo-t3a'
    branch: 'devel'
    targets: ['nimbus_beacon_node', 'nimbus_signing_process']
    frequency: '*-*-* 20:00:00'
