---
# Not pretty but avoids useless files
node_size: |-
  {{ (hostname is search("large")) | ternary("large", "small") }}
node_branch: |-
  {{ (hostname is search("unstable")) | ternary("unstable", (
     (hostname is search("testing")) | ternary("testing", (
     (hostname is search("stable")) | ternary("stable", (
     (hostname is search("libp2p")) | ternary("libp2p", "UNKNOWN")
  )))))) }}

# TEMPORARY switch for Prater Altair transition
beacon_node_cont_image: 'statusteam/nimbus_beacon_node:unstable-{{ node_size }}'
beacon_node_cont_tag: '{{ node_branch }}-{{ node_size }}'
beacon_node_network: 'pyrmont'
beacon_node_log_level: 'INFO'
beacon_node_dist_validators_enabled: true

# Peers
beacon_node_max_peers: 40

# Split by hostname and branch for more central location.
validators_layout:
  "metal-01.he-eu-hel1.nimbus.pyrmont": # 4000 validators each
    "stable":   { start: 0,     end:  4000 }
    "unstable": { start: 4000,  end:  8000 }
    "testing":  { start: 8000,  end: 12000 }
    "libp2p":   { start: 12000, end: 16000 }
  "metal-02.he-eu-hel1.nimbus.pyrmont": # 989  validators each
    "stable":   { start: 16000, end: 16989 }
    "unstable": { start: 16989, end: 17978 }
    "testing":  { start: 17978, end: 18967 }
    "libp2p":   { start: 18967, end: 19956 }
  "metal-03.he-eu-hel1.nimbus.pyrmont": # 10 validators each
    "stable":   { start: 19956, end: 19966 }
    "unstable": { start: 19966, end: 19976 }
    "testing":  { start: 19976, end: 19986 }
    "libp2p":   { start: 19986, end: 19996 }
  "metal-04.he-eu-hel1.nimbus.pyrmont": # 2 validators each
    "stable":   { start: 19996, end: 19997 }
    "unstable": { start: 19997, end: 19998 }
    "testing":  { start: 19998, end: 19999 }
    "libp2p":   { start: 19999, end: 20000 }
