---
# Not pretty but avoids useless files
node_branch: |-
  {{ (hostname is search("unstable")) | ternary("unstable", (
     (hostname is search("testing")) | ternary("testing", (
     (hostname is search("stable")) | ternary("stable", (
     (hostname is search("u-libp2p-u")) | ternary("unstable-libp2p-unstable", (
     (hostname is search("u-libp2p-s")) | ternary("unstable-libp2p-stable", "UNKNOWN")
  )))))))) }}

# TEMPORARY switch for Prater Altair transition
beacon_node_repo_branch: 'unstable' # '{{ node_branch }}'
beacon_node_network: 'prater'
beacon_node_service_name: 'beacon-node-{{ beacon_node_network }}-{{ node_branch }}'

# Ports
beacon_node_discovery_port: 9000
beacon_node_listening_port: 9000
beacon_node_metrics_port:   9200
beacon_node_rest_port:      9300
beacon_node_rpc_port:       9900
beacon_node_rpc_enabled:    true

# Tuning
beacon_node_max_peers: 300
beacon_node_threads: '{{ (beacon_node_repo_branch == "testing") | ternary(4, 1) }}'

# Windows service user
beacon_node_service_user_pass: '{{lookup("bitwarden", "nimbus/windows", field="password")}}'

# Split by hostname for more central location
validators_layout:
  # 2500 validators per node
  'stable-large-01.aws-eu-central-1a.nimbus.prater':     { start:     0, end:  2500 }
  'stable-large-02.aws-eu-central-1a.nimbus.prater':     { start:  2500, end:  5000 }
  'stable-large-03.aws-eu-central-1a.nimbus.prater':     { start:  5000, end:  7500 }
  # 2500 validators per node
  'testing-large-01.aws-eu-central-1a.nimbus.prater':    { start: 12500, end: 15000 }
  'testing-large-02.aws-eu-central-1a.nimbus.prater':    { start: 15000, end: 17500 }
  'testing-large-03.aws-eu-central-1a.nimbus.prater':    { start: 17500, end: 20000 }
  # 2500 validators per node
  "unstable-large-01.aws-eu-central-1a.nimbus.prater":   { start: 25000, end: 27500 }
  "unstable-large-02.aws-eu-central-1a.nimbus.prater":   { start: 27500, end: 30000 }
  "unstable-large-03.aws-eu-central-1a.nimbus.prater":   { start: 30000, end: 32500 }
  # 1250 validators per node
  'u-libp2p-s-large-01.aws-eu-central-1a.nimbus.prater': { start: 37500, end: 38750 }
  # 1250 validators per node
  'u-libp2p-u-large-01.aws-eu-central-1a.nimbus.prater': { start: 38750, end: 40000 }

# Copy correct validators from nimbus-private repo
beacon_node_dist_validators_enabled: true
beacon_node_dist_validators_start: '{{ validators_layout[hostname]["start"] | mandatory }}'
beacon_node_dist_validators_end: '{{ validators_layout[hostname]["end"] | mandatory }}'
