---
# This node is used as replacement for Infura for end-to-end tests.

# Syncing can use a lot of mamory
swap_file_size_mb: 4096

# Geth node
geth_network_name: 'goerli'
geth_cont_name: 'geth-{{ geth_network_name }}'
geth_extra_alias: '{{ geth_cont_name }}'
geth_sync_mode: 'full'
geth_log_level_name: info
geth_websocket_enabled: true
# Geth auth
geth_account_pass: '{{lookup("passwordstore", "service/Nimbus-Geth/password")}}'

# Memory settings
geth_cont_mem_ratio: 0.7

# Geth metrics
geth_source_cont_name: '{{ geth_cont_name }}'
geth_expo_cont_name: '{{ geth_cont_name }}-metrics'
geth_expo_consul_id: '{{ geth_expo_cont_name }}'

# Ports
geth_port: 30303
geth_rpc_port: 8545
geth_websocket_port: 8546
geth_expo_cont_port: 9200
