---
beacon_node_network: 'mainnet'
beacon_node_repo_branch: 'stable'

# Mainnet validators run on a separate fleet.
beacon_node_dist_validators_enabled: false

# Bootnodes should subscribe to all subnets
beacon_node_subscribe_all: true
