---
# This node is used as replacement for Infura for end-to-end tests.

# Syncing can use a lot of mamory
swap_file_size_mb: 4096

# Geth node
geth_service_name: 'nimbus-goerli'
geth_network_name: 'goerli'
geth_sync_mode: 'full'
geth_log_level_name: info
geth_websocket_enabled: true
# Geth auth
geth_account_pass: '{{lookup("passwordstore", "service/Nimbus-Geth/password")}}'
# Allow connections from our Tinc VPN
geth_websocket_origins: '*'
# Memory settings
geth_cont_mem_ratio: 0.8
geth_cache_size: '{{ (ansible_memtotal_mb * 0.25|float) | int }}'

# Geth metrics
geth_expo_service_name: '{{ geth_service_name }}'
geth_expo_source_cont_name: '{{ geth_cont_name }}'
geth_expo_source_data_path: '{{ geth_cont_vol }}/data'

# Ports
geth_port: 30303
geth_rpc_port: 8545
geth_websocket_port: 8546
geth_expo_cont_port: 9200
