---
beacon_node_network: 'pyrmont'
beacon_node_cont_tag: 'libp2p-{{ (hostname is search("large")) | ternary("large", "small") }}'
dist_validators_layout:
  "libp2p-small-01.aws-eu-central-1a.nimbus.pyrmont": { start: 18000, end: 19000 } # 1000 each
  "libp2p-small-02.aws-eu-central-1a.nimbus.pyrmont": { start: 19000, end: 20000 }
