---
# This node is used as replacement for Infura for end-to-end tests.  Syncing can use a lot of mamory
swap_file_size_mb: 4096

# Geth node
geth_service_name: 'nimbus-goerli'
geth_network_name: 'goerli'
geth_sync_mode: 'full'
geth_log_level_name: info
geth_websocket_enabled: true
# Geth auth
geth_account_pass: '{{lookup("bitwarden", "nimbus/geth", field="password")}}'
# Allow connections from our VPN
geth_websocket_origins: '*'
# Memory settings
geth_cont_mem_ratio: 0.8
geth_cache_size: '{{ (ansible_memtotal_mb * 0.25|float) | int }}'

# Geth metrics
geth_expo_service_name: '{{ geth_service_name }}'
geth_expo_source_cont_name: '{{ geth_cont_name }}'
geth_expo_source_data_path: '{{ geth_cont_vol }}/data'

# Ports
geth_port: 30303
geth_rpc_port: 8545
geth_websocket_port: 8546
geth_expo_cont_port: 9200

# Open Ports
open_ports_default_comment: 'Geth Metrics'
open_ports_default_chain: 'VPN'
open_ports_list:
  - { port: '{{ geth_expo_cont_port }}', ipset: 'metrics.hq' }
  - { port: '{{ geth_websocket_port }}', ipset: 'nimbus.pyrmont' }
  - { port: '{{ geth_websocket_port }}', ipset: 'nimbus.prater' }
  - { port: '{{ geth_websocket_port }}', ipset: 'nimbus.rayonism' }
  - { port: '{{ geth_rpc_port }}'      , ipset: 'nimbus.rayonism' }
