---
# Rocketpool
rocketpool_version: 'v1.0.0-pre3'
rocketpool_eth1_network: 'goerli'
# Ports
rocketpool_metrics_port: 9102
rocketpool_eth2_libp2p_port: 59001
rocketpool_eth2_discovery_port: 59001
rocketpool_eth2_metrics_port: 58008
rocketpool_eth2_rest_port: 55052
rocketpool_eth2_rpc_port: 59190
# Eth1 Sync
# TODO query Consul for these
rocketpool_eth2_web3_http_url: 'http://goerli-01.aws-eu-central-1a.nimbus.geth.wg:8545'
rocketpool_eth2_web3_ws_url: 'ws://goerli-01.aws-eu-central-1a.nimbus.geth.wg:8546'
# Eth1 Wallet
rocketpool_password: '{{lookup("passwordstore", "services/Rocketpool/test/Eth1/pass")}}'
rocketpool_wallet: '{{lookup("passwordstore", "services/Rocketpool/test/Eth1/wallet")}}'

# Nimbus Eth1 node
nimbus_eth1_repo_branch: 'master'
nimbus_eth1_network: 'goerli'
nimbus_eth1_max_peers: 160
nimbus_eth1_log_level: 'DEBUG'
nimbus_eth1_metrics_address: '0.0.0.0'
