---
# Beacon Nodes
beacon_node_service_name: 'beacon-node-{{ beacon_node_network }}-{{ beacon_node_repo_branch }}-{{ "%02d"|format(idx|int+1) }}'
beacon_node_network: 'ropsten'
beacon_node_repo_branch: 'unstable'
# Builds
beacon_node_build_frequency: 'daily'
# HTTP RPC support is unstable
beacon_node_web3_urls: '{{ beacon_node_web3_urls_all | reject("match", "^http://") }}'

# Light client data
beacon_node_light_client_data_enabled: true
beacon_node_light_client_data_serve: true
beacon_node_light_client_data_import: 'only-new'
# Validators from nimbus-private repo
beacon_node_dist_validators_enabled: '{{ node.start is defined and node.end is defined }}'
beacon_node_dist_validators_start: '{{ node.start | mandatory }}'
beacon_node_dist_validators_end: '{{ node.end | mandatory }}'
# Ports
beacon_node_discovery_port: '{{ 9000 + idx|int + 1 }}'
beacon_node_listening_port: '{{ 9000 + idx|int + 1 }}'
beacon_node_metrics_port:   '{{ 9200 + idx|int + 1 }}'
beacon_node_rest_port:      '{{ 9300 + idx|int + 1 }}'
beacon_node_rest_address:   '0.0.0.0'

nodes_layout:
  'metal-01.he-eu-hel1.nimbus.ropsten':
    - { start:    0, end:  2500 }
    - { start: 2500, end:  5000 }
    - { start: 5000, end:  7500 }
    - { start: 7500, end: 10000 }
