---
# OpenEthereum
openethereum_service_name: 'nimbus-openeth'
openethereum_chain: 'foundation'
openethereum_mode: 'active'
openethereum_pruning: 'auto'
openethereum_identity: 'Status Nimbus Sync Node'
# Allow connections from our VPN
openethereum_websocket_origins: ['all']
# Memory settings
openethereum_cache_size_ratio: 0.6
openethereum_cont_mem_ratio: 0.8
# APIs
openethereum_rpc_apis: [web3, eth, pubsub, net, parity, parity_pubsub, traces]

# Ports and Addresses
openethereum_p2p_port: 30303
openethereum_rpc_port: 8545
openethereum_rpc_addr: '0.0.0.0'
openethereum_websocket_port: 8546
openethereum_websocket_addr: '0.0.0.0'
openethereum_metrics_port: 3000

# Open Ports
open_ports_default_comment: 'OpenEthereum'
open_ports_default_chain: 'VPN'
open_ports_list:
  - { port: '{{ openethereum_p2p_port }}', chain: 'SERVICES' }
  - { port: '{{ openethereum_metrics_port }}', ipset: 'metrics.hq' }
  - { port: '{{ openethereum_rpc_port }}', ipset: 'nimbus.prater' }
  - { port: '{{ openethereum_rpc_port }}', ipset: 'nimbus.eth1' }
  - { port: '{{ openethereum_rpc_port }}', ipset: 'rocket.prod' }
  - { port: '{{ openethereum_websocket_port }}', ipset: 'nimbus.prater' }
  - { port: '{{ openethereum_websocket_port }}', ipset: 'nimbus.eth1' }
  - { port: '{{ openethereum_websocket_port }}', ipset: 'rocket.prod' }
