---
beacon_node_network: 'pyrmont'
beacon_node_repo_branch: '{{ node.branch is search("libp2p") | ternary("nim-libp2p-auto-bump-unstable", node.branch) }}'
# TODO Simplify this, maybe change branch name.
beacon_node_log_level: 'INFO'
beacon_node_service_name: 'beacon-node-{{ beacon_node_network }}-{{ node.branch }}'
# Ports
beacon_node_discovery_port: '{{ 9000 + port_offset }}'
beacon_node_listening_port: '{{ 9000 + port_offset }}'
beacon_node_metrics_port:   '{{ 9200 + port_offset }}'
beacon_node_rest_port:      '{{ 9300 + port_offset }}'
beacon_node_rpc_port:       '{{ 9900 + port_offset }}'
# Tuning
beacon_node_max_peers: 250
beacon_node_threads: '{{ (node.branch == "testing") | ternary(4, 1) }}'
# Monitoring
beacon_node_validator_monitor_auto: '{{ node.branch == "unstable" }}'
beacon_node_validator_monitor_totals: >-
  {{ node.branch == "unstable" and
   ((node.public_api is defined and node.public_api)
     or
    (node.end is defined and (node.end - node.start) > 64)) }}
# Builds
beacon_node_build_frequency: '{{ node.build_frequency }}'
# Validators from nimbus-private repo
beacon_node_dist_validators_enabled: '{{ node.start is defined and node.end is defined }}'
beacon_node_dist_validators_start: '{{ node.start | mandatory }}'
beacon_node_dist_validators_end: '{{ node.end | mandatory }}'
# HTTP RPC support is unstable
beacon_node_web3_urls: '{{ beacon_node_web3_urls_all | reject("match", "^http://") }}'

# Split by hostname and branch for more central location.
nodes_layout:
  'metal-01.he-eu-hel1.nimbus.pyrmont': # 4000 validators each
    - { branch: 'stable',   start: 0,     end:  4000, build_frequency: '*-*-* 11:00:00' }
    - { branch: 'unstable', start: 4000,  end:  8000, build_frequency: '*-*-* 13:00:00', public_api: true }
    - { branch: 'testing',  start: 8000,  end: 12000, build_frequency: '*-*-* 15:00:00' }
    - { branch: 'libp2p',   start: 12000, end: 16000, build_frequency: '*-*-* 17:00:00' }
  'metal-02.he-eu-hel1.nimbus.pyrmont': # 989  validators each
    - { branch: 'stable',   start: 16000, end: 16989, build_frequency: '*-*-* 11:00:00' }
    - { branch: 'unstable', start: 16989, end: 17978, build_frequency: '*-*-* 13:00:00' }
    - { branch: 'testing',  start: 17978, end: 18967, build_frequency: '*-*-* 15:00:00' }
    - { branch: 'libp2p',   start: 18967, end: 19956, build_frequency: '*-*-* 17:00:00' }
  'metal-03.he-eu-hel1.nimbus.pyrmont': # 10 validators each
    - { branch: 'stable',   start: 19956, end: 19966, build_frequency: '*-*-* 11:00:00' }
    - { branch: 'unstable', start: 19966, end: 19976, build_frequency: '*-*-* 13:00:00' }
    - { branch: 'testing',  start: 19976, end: 19986, build_frequency: '*-*-* 15:00:00' }
    - { branch: 'libp2p',   start: 19986, end: 19996, build_frequency: '*-*-* 17:00:00' }
  'metal-04.he-eu-hel1.nimbus.pyrmont': # 2 validators each
    - { branch: 'stable',   start: 19996, end: 19997, build_frequency: '*-*-* 11:00:00' }
    - { branch: 'unstable', start: 19997, end: 19998, build_frequency: '*-*-* 13:00:00' }
    - { branch: 'testing',  start: 19998, end: 19999, build_frequency: '*-*-* 15:00:00' }
    - { branch: 'libp2p',   start: 19999, end: 20000, build_frequency: '*-*-* 17:00:00' }
