---
beacon_node_network: 'prater'
# TODO This is to avoid too long service names.
beacon_node_repo_branch: '{{ (node.branch == "libp2p") | ternary("nim-libp2p-auto-bump-unstable", node.branch) }}'
# TODO Drop this once all nodes have an number.
service_number: '{{ node.get("num", False) | ternary(("-%02d"|format(node.get("num", 0))), "") }}'
beacon_node_service_name: 'beacon-node-{{ beacon_node_network }}-{{ node.branch }}{{ service_number }}'
# Ports
beacon_node_discovery_port: '{{ 9000 + port_offset }}'
beacon_node_listening_port: '{{ 9000 + port_offset }}'
beacon_node_metrics_port:   '{{ 9200 + port_offset }}'
beacon_node_rest_port:      '{{ 9300 + port_offset }}'
beacon_node_rpc_port:       '{{ 9900 + port_offset }}'
# Firewall
beacon_node_firewall_libp2p_open: '{{ node.get("open_libp2p_ports", true) }}'
# Tuning
beacon_node_max_peers: 300
beacon_node_threads: '{{ (node.branch == "testing") | ternary(4, 1) }}'
# Monitoring
beacon_node_validator_monitor_auto: '{{ node.branch == "unstable" }}'
beacon_node_validator_monitor_totals: >-
  {{ node.branch == "unstable" and
     node.end is defined and
    (node.end - node.start) > 64 }}
# Builds
beacon_node_build_frequency: '{{ node.get("build_freq", "daily") }}'
beacon_node_build_start_time: '{{ node.get("build_start", omit) }}'
# Validators from nimbus-private repo
beacon_node_dist_validators_enabled: '{{ node.start is defined and node.end is defined }}'
beacon_node_dist_validators_start: '{{ node.start | mandatory }}'
beacon_node_dist_validators_end: '{{ node.end | mandatory }}'
# Windows service user
beacon_node_service_user_pass: '{{lookup("bitwarden", "nimbus/windows", field="password")}}'
# HTTP RPC support is unstable
beacon_node_web3_urls: |
  {{ beacon_node_web3_urls_all
  | reject("match",
      ((node.branch == "unstable")
      | ternary("^ws://", "^http://"))
  ) }}

# Split by hostname for more central location
nodes_layout:
  'stable-large-01.aws-eu-central-1a.nimbus.prater':
    - { branch: 'stable',           start:     0, end:  2500 }

  'testing-large-01.aws-eu-central-1a.nimbus.prater':
    - { branch: 'testing',          start: 12500, end: 15000 }

  'unstable-large-01.aws-eu-central-1a.nimbus.prater':
    - { branch: 'unstable',         start: 25000, end: 27500 }

  'metal-01.he-eu-hel1.nimbus.prater':
    - { branch: 'stable',   num: 1, start: 10000, end: 12500, build_freq: '*-*-* 12:00:00' }
    - { branch: 'stable',   num: 2,                           build_freq: '*-*-* 13:00:00' }
    - { branch: 'testing',  num: 1, start: 22500, end: 25000, build_freq: '*-*-* 14:00:00', open_libp2p_ports: false }
    - { branch: 'testing',  num: 2,                           build_freq: '*-*-* 15:00:00' }
    - { branch: 'unstable', num: 1, start: 35000, end: 37500, build_freq: '*-*-* 16:00:00', open_libp2p_ports: false }
    - { branch: 'unstable', num: 2,                           build_freq: '*-*-* 17:00:00' } # Public Beacon API
    - { branch: 'libp2p',   num: 1, start: 38750, end: 40000, build_freq: '*-*-* 18:00:00' } # 1250 validators
    - { branch: 'libp2p',   num: 2,                           build_freq: '*-*-* 19:00:00' }

  'metal-02.he-eu-hel1.nimbus.prater':
    - { branch: 'stable',   num: 1, start:  5000, end:  7500, build_freq: '*-*-* 12:00:00' }
    - { branch: 'stable',   num: 2,                           build_freq: '*-*-* 13:00:00' }
    - { branch: 'testing',  num: 1, start: 17500, end: 20000, build_freq: '*-*-* 14:00:00' }
    - { branch: 'testing',  num: 2,                           build_freq: '*-*-* 15:00:00' } # Public Beacon API
    - { branch: 'unstable', num: 1, start: 30000, end: 32500, build_freq: '*-*-* 16:00:00' }
    - { branch: 'unstable', num: 2,                           build_freq: '*-*-* 17:00:00' }
    - { branch: 'libp2p',   num: 1, start: 37500, end: 38750, build_freq: '*-*-* 18:00:00' } # 1250 validators
    - { branch: 'libp2p',   num: 2,                           build_freq: '*-*-* 19:00:00' }

  'windows-01.gc-us-central1-a.nimbus.prater':
    - { branch: 'stable',           start:  7500, end: 10000, build_start: '13:00:00' }
    - { branch: 'testing',          start: 32500, end: 35000, build_start: '15:00:00' }
    - { branch: 'unstable',         start: 20000, end: 22500, build_start: '16:00:00' }

  'macos-01.ms-eu-dublin.nimbus.prater':
    - { branch: 'stable',           start:  2500, end:  5000, build_start: '13:00:00' }
    - { branch: 'testing',          start: 15000, end: 17500, build_start: '15:00:00' }
    - { branch: 'unstable',         start: 27500, end: 30000, build_start: '16:00:00' }
