---
beacon_node_builds_docker_hub_user: '{{lookup("passwordstore", "cloud/DockerHub/user")}}'
beacon_node_builds_docker_hub_token: '{{lookup("passwordstore", "cloud/DockerHub/token")}}'

# Master host has more memory, but it should be for builds
beacon_node_mem_limit: '{{ (ansible_memtotal_mb * 0.25) | int }}'
beacon_node_mem_reserve: '{{ (ansible_memtotal_mb * 0.2) | int }}'
