---
# Go-Ethereum
geth_service_name: 'geth-kiln-{{ "%02d"|format(idx|int) }}'
geth_network_id: 1337802
geth_sync_mode: 'snap'
geth_log_level_name: info
# Container
geth_cont_tag: 'merge-kiln-v2'
geth_cont_image: 'statusteam/go-client:{{ geth_cont_tag }}'
# Geth auth
geth_account_pass: '{{lookup("bitwarden", "nimbus/geth", field="password")}}'
# Memory settings
geth_cont_mem_ratio: 0.3
# Genesis
geth_init_enabled: true
geth_init_url: 'https://config.kiln.themerge.dev/el/genesis/geth.json'
geth_init_sha256: 'f77edfa0fd6bfa787961f994abeacb521d6a63e895a04fcb8498f0adb971fb4b'
# Bootsrap
geth_bootnodes: ['enode://c354db99124f0faf677ff0e75c3cbbd568b2febc186af664e0c51ac435609badedc67a18a63adb64dacc1780a28dcefebfc29b83fd1a3f4aa3c0eb161364cf94@164.92.130.5:30303']
# Enable engine API
geth_rcp_api: 'eth,net,web3,personal,admin,engine'
geth_websocket_api: 'eth,net,web3,personal,admin,engine'
# Ports
geth_port: '{{ 30303 + idx|int }}'
geth_metrics_port: '{{ 6060 + idx|int }}'
geth_rpc_enabled: true
geth_rpc_addr: '0.0.0.0'
geth_rpc_port: '{{ 8545 + idx|int }}'
geth_websocket_enabled: true
geth_websocket_addr: '0.0.0.0'
geth_websocket_port: '{{ 9546 + idx|int }}'
