---
# TRACE needs more disk space
bootstrap__rsyslog_docker_logs_path: '/docker/log'
# The volume of logs is too big and Nimbus team doesn't use their own cluster
bootstrap__rsyslog_docker_logstash_send: false

# lower local retention to save space
bootstrap__logrotate_frequency: 'hourly'
bootstrap__logrotate_count: 3
bootstrap__logrotate_mbytes: 500

# Nimbus ------------------------------
beacon_node_cont_name: 'beacon-node-{{ beacon_node_network }}-{{ beacon_node_cont_tag }}'
beacon_node_log_level: DEBUG
beacon_node_timer_rebuild: true

# ports
beacon_node_rpc_port: '11000'
beacon_node_metrics_port : '9300'
beacon_node_listening_port: '9100'
beacon_node_discovery_port: '9100'

# Infura URL
beacon_node_web3_url: '{{ lookup("passwordstore", "service/Nimbus/infura-url") }}'

# resource limits
beacon_node_mem_limit: '{{ (ansible_memtotal_mb * 0.60) | int }}'
beacon_node_mem_reserve: '{{ (ansible_memtotal_mb * 0.4) | int }}'

# Validators --------------------------
dist_validators_name: '{{ beacon_node_network }}_deposits'
dist_validators_data_path: '{{ beacon_node_cont_vol }}/data/{{ beacon_node_data_folder }}'
