---
- include_tasks: consul/posix.yml
  when: ansible_system in ['Linux', 'Darwin']
  loop: '{{ geth_node_api_consul_names }}'
  loop_control:
    loop_var: 'service_name'

- include_tasks: consul/windows.yml
  when: ansible_system == 'Win32NT'
  loop: '{{ geth_node_api_consul_names }}'
  loop_control:
    loop_var: 'service_name'

- name: Extract Goerli Geth WebSocket URL
  set_fact:
    # our nodes first (will be used by default) then an infura node
    beacon_node_web3_urls_all: "{{ geth_api_addresses + [ selected_infura_url ] }}"
