---
#nimbus_db_purge_node_service_name: ~
#nimbus_db_purge_node_service_path: ~
#nimbus_db_purge_node_network_name: ~
#nimbus_db_purge_truster_node_api_url: 'http://localhost:1234'

nimbus_db_purge_timer_name: 'nimbus-db-purge'
nimbus_db_purge_timer_enabled: true
nimbus_db_purge_timer_timeout: 600
nimbus_db_purge_timer_frequency: 'weekly'
nimbus_db_purge_timer_script_path: '{{ nimbus_db_purge_node_service_path | mandatory }}/purge_sync.sh'
