---
- name: Pre-playbook checks
  hosts: localhost
  tasks:
    - name: 'Verify Ansible version is 2.8 or newer'
      assert:
        that: 'ansible_version.full is version_compare("2.8", ">=")'
        msg: 'Your Ansible version is lower than 2.8. Upgrade it.'

- name: Configure geth nodes
  become: true
  hosts:
    - nimbus-geth-goerli
    - nimbus-geth-mainnet
  roles:
    - { role: swap-file,                tags: swap-file }
    - { role: infra-role-geth,          tags: infra-role-geth }
    - { role: infra-role-geth-exporter, tags: infra-role-geth-exporter }
