---
- name: Configure Nimbus master
  hosts: nimbus-master
  roles:
    - { role: origin-cert }
    - { role: nimbus-stats, tags: nimbus-stats }

- name: Configure Nimbus cluster
  hosts:
    - nimbus-master
    - nimbus-slaves
  tasks:
    - include_role:
        name: infra-role-beacon-node
        tags: beacon-node
      with_sequence: count=2
      vars:
        beacon_node_network: 'testnet0'
        beacon_node_metrics_port : '{{ 9200 - 1 + item|int }}'
        beacon_node_listening_port: '{{ 9000 - 1 + item|int }}'
        beacon_node_discovery_port: '{{ 9000 - 1 + item|int }}'
        beacon_node_cont_name: 'beacon-node-{{ beacon_node_network}}-{{ item }}'

    - include_role:
        name: infra-role-beacon-node
        tags: beacon-node
      with_sequence: count=2
      vars:
        beacon_node_network: 'testnet1'
        beacon_node_metrics_port : '{{ 9300 - 1 + item|int }}'
        beacon_node_listening_port: '{{ 9100 - 1 + item|int }}'
        beacon_node_discovery_port: '{{ 9100 - 1 + item|int }}'
        beacon_node_cont_name: 'beacon-node-{{ beacon_node_network}}-{{ item }}'
