---
- name: Configure Nimbus master
  hosts: nimbus-master
  roles:
    - origin-cert
    - infra-role-eth2-testnet-site

- name: Configure Nimbus cluster
  hosts: nimbus-slaves
  roles:
    - infra-role-beacon-node
