---
- name: Add CloudFlare Origin certs
  hosts: all
  roles:
    - origin-cert

#- name: Configure Nimbus master
#  hosts: nimbus-master
#  roles:
#    - nimbus

- name: Configure Nimbus cluster
  hosts: nimbus-nodes
  roles:
    - nimbus
