---
- name: 'Verify Ansible versions'
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Configure network mainnet bootnodes
  become: true
  hosts: 'nimbus.mainnet'
  roles:
    - { role: get-geth-web3-urls,     tags: [ get-geth-web3-urls ] }
    - { role: infra-role-beacon-node, tags: [ infra-role-beacon-node, beacon-node ] }
