---
- name: Configure Nimbus master
  hosts: nimbus-master
  roles:
    - { role: origin-cert }
    # - { role: infra-role-eth2-testnet-site }
    - { role: nimbus-stats, tags: nimbus-stats }
    - { role: infra-role-beacon-node,
        beacon_node_network: 'testnet0',
        beacon_node_build_flavour: 'rlpx',
        beacon_node_total_nodes: 2,
        beacon_node_running_nodes: 2,
        beacon_node_discovery_port: 9000,
        beacon_node_listening_port: 9000 }
    - { role: infra-role-beacon-node,
        beacon_node_network: 'testnet1',
        beacon_node_build_flavour: 'rlpx',
        beacon_node_total_nodes: 5,
        beacon_node_running_nodes: 2,
        beacon_node_discovery_port: 9100,
        beacon_node_listening_port: 9100 }

- name: Configure Nimbus cluster
  hosts: nimbus-slaves
  roles:
    - { role: infra-role-beacon-node,
        beacon_node_network: 'testnet0',
        beacon_node_build_flavour: 'rlpx',
        beacon_node_total_nodes: 2,
        beacon_node_running_nodes: 2,
        beacon_node_discovery_port: 9000,
        beacon_node_listening_port: 9000 }
    - { role: infra-role-beacon-node,
        beacon_node_network: 'testnet1',
        beacon_node_build_flavour: 'rlpx',
        beacon_node_total_nodes: 10,
        beacon_node_running_nodes: 2,
        beacon_node_discovery_port: 9100,
        beacon_node_listening_port: 9100 }
