---
- name: Configure Nimbus master
  hosts: nimbus-master
  roles:
    - { role: origin-cert }
    - { role: nimbus-stats, tags: nimbus-stats }
    # - { role: infra-role-eth2-testnet-site }
  tasks:
    - include_role:
        name: infra-role-beacon-node
      with_sequence: count=2
      vars:
        beacon_node_network: 'testnet0'
        beacon_node_public_tcp_port: '{{ 9000 - 1 + item|int }}'
        beacon_node_public_udp_port: '{{ 9000 - 1 + item|int }}'
        beacon_node_cont_name: 'beacon-node-{{ beacon_node_build_flavour }}-{{ beacon_node_network}}-{{ item }}'

    - include_role:
        name: infra-role-beacon-node
      with_sequence: count=2
      vars:
        beacon_node_network: 'testnet1'
        beacon_node_public_tcp_port: '{{ 9100 - 1 + item|int }}'
        beacon_node_public_udp_port: '{{ 9100 - 1 + item|int }}'
        beacon_node_cont_name: 'beacon-node-{{ beacon_node_build_flavour }}-{{ beacon_node_network}}-{{ item }}'

- name: Configure Nimbus cluster
  hosts: nimbus-slaves
  tasks:
    - include_role:
        name: infra-role-beacon-node
      with_sequence: count=2
      vars:
        beacon_node_network: 'testnet0'
        beacon_node_public_tcp_port: '{{ 9000 - 1 + item|int }}'
        beacon_node_public_udp_port: '{{ 9000 - 1 + item|int }}'
        beacon_node_cont_name: 'beacon-node-{{ beacon_node_build_flavour }}-{{ beacon_node_network}}-{{ item }}'

    - include_role:
        name: infra-role-beacon-node
      with_sequence: count=2
      vars:
        beacon_node_network: 'testnet1'
        beacon_node_public_tcp_port: '{{ 9100 - 1 + item|int }}'
        beacon_node_public_udp_port: '{{ 9100 - 1 + item|int }}'
        beacon_node_cont_name: 'beacon-node-{{ beacon_node_build_flavour }}-{{ beacon_node_network}}-{{ item }}'
