---
- name: Pre-playbook checks
  hosts: localhost
  tasks:
    - name: 'Verify Ansible version is 2.8 or newer'
      assert:
        that: 'ansible_version.full is version_compare("2.8", ">=")'
        msg: 'Your Ansible version is lower than 2.8. Upgrade it.'

- name: Configure beacon node builds
  hosts: nimbus-master
  roles:
    - { role: beacon-node-builds,     tags: beacon-node-builds }

- name: Configure network medalla using master
  hosts: nimbus.test[0:3]
  vars:
    beacon_node_cont_tag: 'master'
    # Legacy binary necessary for medalla network
    beacon_node_cont_entrypoint: '/usr/local/bin/nimbus_beacon_node_spec_0_12_3'
  roles:
    - { role: infra-role-beacon-node, tags: [ infra-role-beacon-node, beacon-node ] }
    - { role: network-debug-script,   tags: [ network-debug-script ] }

- name: Configure network medalla using devel
  hosts: nimbus.test[4:7]
  vars:
    beacon_node_cont_tag: 'devel'
    # Legacy binary necessary for medalla network
    beacon_node_cont_entrypoint: '/usr/local/bin/nimbus_beacon_node_spec_0_12_3'
  roles:
    - { role: infra-role-beacon-node, tags: [ infra-role-beacon-node, beacon-node ] }
    - { role: network-debug-script,   tags: [ network-debug-script ] }

- name: Configure network medalla using libp2p
  hosts: nimbus.test[8:9]
  vars:
    beacon_node_cont_tag: 'libp2p'
    # Legacy binary necessary for medalla network
    beacon_node_cont_entrypoint: '/usr/local/bin/nimbus_beacon_node_spec_0_12_3'
  roles:
    - { role: infra-role-beacon-node, tags: [ infra-role-beacon-node, beacon-node ] }
    - { role: network-debug-script,   tags: [ network-debug-script ] }
