---
- name: Pre-playbook checks
  hosts: localhost
  tasks:
    - name: 'Verify Ansible version is 2.8 or newer'
      assert:
        that: 'ansible_version.full is version_compare("2.8", ">=")'
        msg: 'Your Ansible version is lower than 2.8. Upgrade it.'

- name: Configure shared testnet3 using master
  hosts: nimbus.test[0:3]
  vars:
    beacon_node_repo_branch: 'master'
  roles:
    - { role: infra-role-beacon-node, tags: [ infra-role-beacon-node, beacon-node ] }
    - { role: network-debug-script,   tags: [ network-debug-script ] }

- name: Configure shared testnet2 using devel
  hosts: nimbus.test[4:7]
  vars:
    beacon_node_repo_branch: 'devel'
  roles:
    - { role: infra-role-beacon-node, tags: [ infra-role-beacon-node, beacon-node ] }
    - { role: network-debug-script,   tags: [ network-debug-script ] }

- name: Configure shared testnet3 using libp2p
  hosts: nimbus.test[8:9]
  vars:
    beacon_node_repo_branch: 'libp2p'
  roles:
    - { role: infra-role-beacon-node, tags: [ infra-role-beacon-node, beacon-node ] }
    - { role: network-debug-script,   tags: [ network-debug-script ] }
