---
- name: Pre-playbook checks
  hosts: localhost
  tasks:
    - name: 'Verify Ansible version is 2.8 or newer'
      assert:
        that: 'ansible_version.full is version_compare("2.8", ">=")'
        msg: 'Your Ansible version is lower than 2.8. Upgrade it.'

- name: Configure beacon node builds
  hosts: nimbus-master
  roles:
    - { role: beacon-node-builds,     tags: beacon-node-builds }

- name: Configure network medalla using master
  hosts: nimbus.test[0:3]
  vars:
    beacon_node_repo_branch: 'master'
  roles:
    - { role: infra-role-beacon-node, tags: [ infra-role-beacon-node, beacon-node ] }
    - { role: network-debug-script,   tags: [ network-debug-script ] }

- name: Configure network medalla using devel
  hosts: nimbus.test[4:7]
  vars:
    beacon_node_repo_branch: 'devel'
  roles:
    - { role: infra-role-beacon-node, tags: [ infra-role-beacon-node, beacon-node ] }
    - { role: network-debug-script,   tags: [ network-debug-script ] }

- name: Configure network medalla using libp2p
  hosts: nimbus.test[8:9]
  vars:
    beacon_node_repo_branch: 'libp2p'
  roles:
    - { role: infra-role-beacon-node, tags: [ infra-role-beacon-node, beacon-node ] }
    - { role: network-debug-script,   tags: [ network-debug-script ] }

- name: Configure network toledo using develop
  hosts: nimbus-slaves-toledo
  vars:
    beacon_node_network: 'toledo'
    beacon_node_repo_branch: 'devel'
    dist_validators_layout:
        "toledo-01.aws-eu-central-1a.nimbus.test": { start: 0, end: 1024 }
        "toledo-02.aws-eu-central-1a.nimbus.test": { start: 1024, end: 2047 }
  roles:
    - { role: distribute-validators,  tags: [ distribute-validators ] }
    - { role: infra-role-beacon-node, tags: [ infra-role-beacon-node, beacon-node ] }
