---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Deploy beacon node build nodes
  become: true
  hosts:
    - testing-large-01.aws-eu-central-1a.nimbus.pyrmont
  roles:
    - role: swap-file
      tags: swap-file
    - role: beacon-node-builds
      tags: beacon-node-builds

- name: Deploy prater Linux beacon nodes
  become: true
  # To avoid clashing/duplicate validators.
  any_errors_fatal: true
  hosts:
    - nimbus-prater-stable
    - nimbus-prater-testing
    - nimbus-prater-unstable
  roles:
    - role: get-geth-web3-urls
      tags: get-geth-web3-urls
    - role: infra-role-beacon-node
      tags: [ infra-role-beacon-node, beacon-node ]

- name: Deploy mainnet linux beacon nodes
  become: true
  hosts: nimbus-prater-metal
  roles:
    - { role: get-geth-web3-urls,     tags: [ get-geth-web3-urls ] }
  tasks:
    - include_role: name=infra-role-beacon-node-linux
      tags: [ beacon-node, infra-role-beacon-node-linux ]
      vars:
        beacon_node_repo_branch: '{{ node.branch }}'
        beacon_node_build_frequency: '{{ node.build_frequency }}'
        beacon_node_discovery_port: '{{ 9000 + port_offset }}'
        beacon_node_listening_port: '{{ 9000 + port_offset }}'
        beacon_node_metrics_port:   '{{ 9200 + port_offset }}'
        beacon_node_rpc_port:       '{{ 9900 + port_offset }}'
        beacon_node_dist_validators_start: '{{ node.start }}'
        beacon_node_dist_validators_end: '{{ node.end }}'
      with_items:
        - { branch: 'stable',   start: 10000, end: 12500, build_frequency: '*-*-* 12:00:00' }
        - { branch: 'testing',  start: 22500, end: 25000, build_frequency: '*-*-* 16:00:00' }
        - { branch: 'unstable', start: 35000, end: 37500, build_frequency: '*-*-* 14:00:00' }
      loop_control:
        loop_var: node
        index_var: port_offset

- name: Deploy prater Windows beacon nodes
  become: true
  hosts: nimbus-prater-windows
  tasks:
    - include_role: name=infra-role-beacon-node-windows
      tags: [ beacon-node, infra-role-beacon-node-windows ]
      vars:
        beacon_node_repo_branch: '{{ node.branch }}'
        beacon_node_discovery_port: '{{ 9000 + port_offset }}'
        beacon_node_listening_port: '{{ 9000 + port_offset }}'
        beacon_node_metrics_port:   '{{ 9200 + port_offset }}'
        beacon_node_rpc_port:       '{{ 9900 + port_offset }}'
      with_items:
        - { branch: 'stable' }
        - { branch: 'unstable' }
        - { branch: 'testing' }
      loop_control:
        loop_var: node
        index_var: port_offset
