---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Deploy pyrmont Metal beacon nodes
  become: true
  serial: '{{ serial|default(4) }}'
  hosts:
    - nimbus-pyrmont-metal
  roles:
    - { role: redirect-ports,     tags: redirect-ports    }
    - { role: get-geth-api-urls,  tags: get-geth-api-urls }
  tasks:
    - include_role: name=infra-role-beacon-node-linux
      tags: [ beacon-node, infra-role-beacon-node-linux ]
      with_items: '{{ nodes_layout[hostname] }}'
      loop_control:
        loop_var: node
        index_var: port_offset
