---
- name: Pre-playbook checks
  hosts: localhost
  tasks:
    - name: 'Verify Ansible version is 2.8 or newer'
      assert:
        that: 'ansible_version.full is version_compare("2.8", ">=")'
        msg: 'Your Ansible version is lower than 2.8. Upgrade it.'

- name: Configure build nodes
  become: true
  hosts:
    - testing-large-01.aws-eu-central-1a.nimbus.pyrmont
    - testing-small-01.aws-eu-central-1a.nimbus.pyrmont
  roles:
    - { role: beacon-node-builds,     tags: beacon-node-builds }

- name: Configure network pyrmont
  become: true
  hosts:
    - nimbus-pyrmont-stable
    - nimbus-pyrmont-testing
    - nimbus-pyrmont-unstable
    - nimbus-pyrmont-unstable-libp2p
  pre_tasks:
    - name: Discover Goerli Geth WebSocket endpoint
      tags: [ infra-role-beacon-node, beacon-node ]
      uri:
        url: '{{ consul_catalog_url }}/service/geth-goerli-ws'
      register: geth_service

    - name: Extract Goerli Geth WebSocket URL
      tags: [ infra-role-beacon-node, beacon-node ]
      set_fact:
        beacon_node_web3_url: 'ws://{{ geth_service.json[0].ServiceAddress }}:{{ geth_service.json[0].ServicePort }}'
  roles:
    - { role: distribute-validators,  tags: [ distribute-validators ] }
    - { role: infra-role-beacon-node, tags: [ infra-role-beacon-node, beacon-node ] }
