---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Configure build nodes
  become: true
  hosts:
    - testing-large-01.aws-eu-central-1a.nimbus.pyrmont
    - testing-small-01.aws-eu-central-1a.nimbus.pyrmont
  roles:
    - role: swap-file
      tags: swap-file
    - role: beacon-node-builds
      tags: beacon-node-builds

- name: Configure network pyrmont
  become: true
  # To avoid clashing/duplicate validators.
  any_errors_fatal: true
  hosts: 'nimbus.pyrmont'
  roles:
    - { role: distribute-validators,  tags: [ distribute-validators ] }
    - { role: get-geth-web3-urls,     tags: [ get-geth-web3-urls ] }
    - { role: infra-role-beacon-node, tags: [ infra-role-beacon-node, beacon-node ] }
