---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Configure build nodes
  become: true
  hosts:
    - testing-large-01.aws-eu-central-1a.nimbus.pyrmont
    - testing-small-01.aws-eu-central-1a.nimbus.pyrmont
  roles:
    - role: swap-file
      tags: swap-file
    - role: beacon-node-builds
      tags: beacon-node-builds

- name: Configure network pyrmont
  become: true
  # To avoid clashing/duplicate validators.
  any_errors_fatal: true
  hosts:
    - nimbus-pyrmont-stable
    - nimbus-pyrmont-testing
    - nimbus-pyrmont-unstable
    - nimbus-pyrmont-libp2p
  roles:
    - { role: get-geth-web3-urls,     tags: [ get-geth-web3-urls ] }
    - { role: infra-role-beacon-node, tags: [ infra-role-beacon-node, beacon-node ] }

- name: Deploy pyrmont Metal beacon nodes
  become: true
  hosts:
    - nimbus-pyrmont-metal
  tasks:
    - include_role: name=infra-role-beacon-node-linux
      tags: [ beacon-node, infra-role-beacon-node-linux ]
      vars:
        beacon_node_dist_validators_enabled: false
        beacon_node_repo_branch: '{{ node.branch }}'
        beacon_node_discovery_port: '{{ 9000 + port_offset }}'
        beacon_node_listening_port: '{{ 9000 + port_offset }}'
        beacon_node_metrics_port:   '{{ 9200 + port_offset }}'
        beacon_node_rpc_port:       '{{ 9900 + port_offset }}'
      with_items:
        - { branch: 'stable'   }
        - { branch: 'unstable' }
        - { branch: 'testing'  }
      loop_control:
        loop_var: node
        index_var: port_offset
