---
- name: nginx
  src: git@github.com:status-im/infra-role-nginx.git
  version: 3043c998cbc92a634a71dc48363b3e2525696d26
  scm: git

- name: origin-certs
  src: git@github.com:status-im/infra-role-origin-certs.git
  version: 60587f86e085255b537cc37647003af105214d20
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: c5f6f1c59d91f50f647def54c8b5b32998465912
  scm: git

- name: infra-role-bootstrap-windows
  src: git@github.com:status-im/infra-role-bootstrap-windows.git
  version: cf9df32cfed59f4e7cc93f36b3fd8795d46fedde
  scm: git

- name: infra-role-bootstrap-macos
  src: git@github.com:status-im/infra-role-bootstrap-macos.git
  version: 39182e507379eac63111916767006383899b0827
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: a169a04cc4a3967db8a1486ac3732233ff515f60
  scm: git

- name: oauth-proxy
  src: git@github.com:status-im/infra-role-oauth-proxy.git
  version: b1b60917e839f9205af3952574b1f2c893aaedba
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 61a248a697d37c98b575be942bb6e86deb512380
  scm: git

- name: infra-role-beacon-node-linux
  src: git@github.com:status-im/infra-role-beacon-node-linux.git
  version: 5f50a97c07493d65a254b85c90f55dedff1728b7
  scm: git

- name: infra-role-beacon-node-windows
  src: git@github.com:status-im/infra-role-beacon-node-windows.git
  version: 5eab965d005c4f076d4c12ce8a115fc42c8cdc07
  scm: git

- name: infra-role-beacon-node-macos
  src: git@github.com:status-im/infra-role-beacon-node-macos.git
  version: 6a0a46e046c6d944bf4eca13f0ab17a018e4140d
  scm: git

- name: infra-role-nimbus-eth1
  src: git@github.com:status-im/infra-role-nimbus-eth1.git
  version: 3a1a651d92f7533b974ad74e69956fb815bd9fbe
  scm: git

- name: infra-role-dist-validators
  src: git@github.com:status-im/infra-role-dist-validators.git
  version: f5e6c3063ecbb475af0dba7a62e5e587af52b631
  scm: git

- name: infra-role-rocketpool
  src: git@github.com:status-im/infra-role-rocketpool.git
  version: 09b4ab49a1c234185294443507495ebb32393e54
  scm: git

- name: infra-role-winsw
  src: git@github.com:status-im/infra-role-winsw.git
  version: 2f89ee1ffac7d678ed25b63a718b1018e1ec860f
  scm: git

- name: kibana
  src: git@github.com:status-im/infra-role-kibana.git
  version: c996858afae7effa7984403917827e79c732b957
  scm: git

- name: elasticsearch
  src: git@github.com:status-im/infra-role-elasticsearch.git
  version: f7391551f8d834731d8ece3eec91a2075d093973
  scm: git

- name: elasticsearch-lb
  src: git@github.com:status-im/infra-role-elasticsearch-lb.git
  version: 0ad1758c0450dc8cc8b392a3fc5f89cb793c2e28
  scm: git

- name: systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  version: fbcc0ce58776c59cf6e0ff9b7d605663ac3e7b95
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 7b63fb7b5f0c525aa191e1a410fd79f7eab8d11a
  scm: git

- name: infra-role-geth
  src: git@github.com:status-im/infra-role-geth.git
  version: 746959aa0eb740a9be3015679750bdcc7f14278e
  scm: git

- name: infra-role-geth-exporter
  src: git@github.com:status-im/infra-role-geth-exporter.git
  version: 30e6a08e9b2badffbd32472fff640aefef26fd37
  scm: git
