---
- name: nginx
  src: git@github.com:status-im/infra-role-nginx.git
  version: 3043c998cbc92a634a71dc48363b3e2525696d26
  scm: git

- name: origin-certs
  src: git@github.com:status-im/infra-role-origin-certs.git
  version: f7dcb7e1944d2ec0655bf8e7ce6f45a1317b65b9
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: a404e479eee9bc00ef0bc911fc5b0c5e1ca8dfea
  scm: git

- name: infra-role-bootstrap-windows
  src: git@github.com:status-im/infra-role-bootstrap-windows.git
  version: a3b0e99dadf51e3113d0359fc314821b82f396e3
  scm: git

- name: infra-role-bootstrap-macos
  src: git@github.com:status-im/infra-role-bootstrap-macos.git
  version: 2360d1b895fa9ab56da9aca2a42c9abaa62a1add
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: c0c96298270c1763e819967ff1cad4ad876506b0
  scm: git

- name: oauth-proxy
  src: git@github.com:status-im/infra-role-oauth-proxy.git
  version: 05ef1410abe09db6df6e58ca14c556b7e2c383d7
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 241dffb0f865f8558b5e373d20fefed0a08a21ef
  scm: git

- name: infra-role-beacon-node-linux
  src: git@github.com:status-im/infra-role-beacon-node-linux.git
  version: d993d06dc2d05fcad881233a65f8d9cc6c26d844
  scm: git

- name: infra-role-beacon-node-windows
  src: git@github.com:status-im/infra-role-beacon-node-windows.git
  version: f6dd9dd6440ebf06da859ff6ea04d8d8fd933b48
  scm: git

- name: infra-role-beacon-node-macos
  src: git@github.com:status-im/infra-role-beacon-node-macos.git
  version: f4fd894c3ed1ebe570320f64106ae56058485e08
  scm: git

- name: infra-role-nimbus-eth1
  src: git@github.com:status-im/infra-role-nimbus-eth1.git
  version: 3a1a651d92f7533b974ad74e69956fb815bd9fbe
  scm: git

- name: infra-role-dist-validators
  src: git@github.com:status-im/infra-role-dist-validators.git
  version: f5e6c3063ecbb475af0dba7a62e5e587af52b631
  scm: git

- name: infra-role-rocketpool
  src: git@github.com:status-im/infra-role-rocketpool.git
  version: 09b4ab49a1c234185294443507495ebb32393e54
  scm: git

- name: infra-role-winsw
  src: git@github.com:status-im/infra-role-winsw.git
  version: 2f89ee1ffac7d678ed25b63a718b1018e1ec860f
  scm: git

- name: kibana
  src: git@github.com:status-im/infra-role-kibana.git
  version: cb2cbb374199f5b2b627cc3d2bc9fb325bca82c1
  scm: git

- name: elasticsearch
  src: git@github.com:status-im/infra-role-elasticsearch.git
  version: f38d712b12e205d245cc692b6e99049acaf9401e
  scm: git

- name: elasticsearch-hq
  src: git@github.com:status-im/infra-role-elasticsearch-hq.git
  version: a92df1ac36c9a8e86fabefb54e24fe33d572ce10
  scm: git

- name: elasticsearch-lb
  src: git@github.com:status-im/infra-role-elasticsearch-lb.git
  version: 0ad1758c0450dc8cc8b392a3fc5f89cb793c2e28
  scm: git

- name: systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  version: fbcc0ce58776c59cf6e0ff9b7d605663ac3e7b95
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 7b63fb7b5f0c525aa191e1a410fd79f7eab8d11a
  scm: git

- name: infra-role-geth
  src: git@github.com:status-im/infra-role-geth.git
  version: 746959aa0eb740a9be3015679750bdcc7f14278e
  scm: git

- name: infra-role-geth-exporter
  src: git@github.com:status-im/infra-role-geth-exporter.git
  version: 30e6a08e9b2badffbd32472fff640aefef26fd37
  scm: git
