---
- name: nginx
  src: git@github.com:status-im/infra-role-nginx.git
  version: 3043c998cbc92a634a71dc48363b3e2525696d26
  scm: git

- name: origin-certs
  src: git@github.com:status-im/infra-role-origin-certs.git
  version: f7dcb7e1944d2ec0655bf8e7ce6f45a1317b65b9
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: dc060de82cbf07dac570c8be2214fe2c250115a2
  scm: git

- name: infra-role-bootstrap-windows
  src: git@github.com:status-im/infra-role-bootstrap-windows.git
  version: bc80d3a8d39d5133ca8ae5c9fc22b8d2d52d7a68
  scm: git

- name: infra-role-bootstrap-macos
  src: git@github.com:status-im/infra-role-bootstrap-macos.git
  version: a0ab4fb83bf5d9e4a7fdc77eb52cc3333e7205b6
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: c0c96298270c1763e819967ff1cad4ad876506b0
  scm: git

- name: oauth-proxy
  src: git@github.com:status-im/infra-role-oauth-proxy.git
  version: 05ef1410abe09db6df6e58ca14c556b7e2c383d7
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 241dffb0f865f8558b5e373d20fefed0a08a21ef
  scm: git

- name: infra-role-beacon-node-linux
  src: git@github.com:status-im/infra-role-beacon-node-linux.git
  version: 109f65e60ae968be33651a4e7ca20485e6144325
  scm: git

- name: infra-role-beacon-node-windows
  src: git@github.com:status-im/infra-role-beacon-node-windows.git
  version: 6b5e2adbb5185ec1a1a6e6d7eef7f86095fa395f
  scm: git

- name: infra-role-beacon-node-macos
  src: git@github.com:status-im/infra-role-beacon-node-macos.git
  version: 2e36f3fa755af04f311a8a471c8782ddb5aee477
  scm: git

- name: infra-role-nimbus-eth1
  src: git@github.com:status-im/infra-role-nimbus-eth1.git
  version: 3a1a651d92f7533b974ad74e69956fb815bd9fbe
  scm: git

- name: infra-role-dist-validators
  src: git@github.com:status-im/infra-role-dist-validators.git
  version: f5e6c3063ecbb475af0dba7a62e5e587af52b631
  scm: git

- name: infra-role-rocketpool
  src: git@github.com:status-im/infra-role-rocketpool.git
  version: 454a8470ea4e3e5ae2b1eded66ecad643ecf28ff
  scm: git

- name: infra-role-winsw
  src: git@github.com:status-im/infra-role-winsw.git
  version: 2f89ee1ffac7d678ed25b63a718b1018e1ec860f
  scm: git

- name: kibana
  src: git@github.com:status-im/infra-role-kibana.git
  version: cb2cbb374199f5b2b627cc3d2bc9fb325bca82c1
  scm: git

- name: elasticsearch
  src: git@github.com:status-im/infra-role-elasticsearch.git
  version: 0d60d773b68a70352501997cdb54f6c91597e763
  scm: git

- name: elasticsearch-hq
  src: git@github.com:status-im/infra-role-elasticsearch-hq.git
  version: a92df1ac36c9a8e86fabefb54e24fe33d572ce10
  scm: git

- name: elasticsearch-lb
  src: git@github.com:status-im/infra-role-elasticsearch-lb.git
  version: e7912ebd3eb12e6bf30307ea9df860e1b3931041
  scm: git

- name: systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  version: cf1798b1eb49af97a62675fa865a89919d7e0bd1
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 7b63fb7b5f0c525aa191e1a410fd79f7eab8d11a
  scm: git

- name: infra-role-geth
  src: git@github.com:status-im/infra-role-geth.git
  version: 47b3de7059cdef2aae85865eab7bd205e04109d9
  scm: git

- name: infra-role-geth-exporter
  src: git@github.com:status-im/infra-role-geth-exporter.git
  version: 30e6a08e9b2badffbd32472fff640aefef26fd37
  scm: git
