---
- name: nginx
  src: git@github.com:status-im/infra-role-nginx.git
  version: 3043c998cbc92a634a71dc48363b3e2525696d26
  scm: git

- name: origin-certs
  src: git@github.com:status-im/infra-role-origin-certs.git
  version: f7dcb7e1944d2ec0655bf8e7ce6f45a1317b65b9
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: 2468bfb373dd071a7ab7a068cdcc59472fd76a05
  scm: git

- name: infra-role-bootstrap-windows
  src: git@github.com:status-im/infra-role-bootstrap-windows.git
  version: bc80d3a8d39d5133ca8ae5c9fc22b8d2d52d7a68
  scm: git

- name: infra-role-bootstrap-macos
  src: git@github.com:status-im/infra-role-bootstrap-macos.git
  version: deb5d75574413e471587ebccf32a9bc680cd08e5
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: db787311e9ee59c60ab6f4eaf3dea064b7017ba0
  scm: git

- name: oauth-proxy
  src: git@github.com:status-im/infra-role-oauth-proxy.git
  version: 05ef1410abe09db6df6e58ca14c556b7e2c383d7
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 87f4498f90f0cbb66a1ddb425e8953b04ced1891
  scm: git

- name: infra-role-beacon-node-linux
  src: git@github.com:status-im/infra-role-beacon-node-linux.git
  version: 3af4e926c1a017335747154a5e9a654ac04ecf0e
  scm: git

- name: infra-role-beacon-node-windows
  src: git@github.com:status-im/infra-role-beacon-node-windows.git
  version: 2bbbc277dfb9b4c12d984acb5698ad76190bf1f1
  scm: git

- name: infra-role-beacon-node-macos
  src: git@github.com:status-im/infra-role-beacon-node-macos.git
  version: 39180ccb244e2e689f7f8e068011e2d613e08fd9
  scm: git

- name: infra-role-nimbus-eth1
  src: git@github.com:status-im/infra-role-nimbus-eth1.git
  version: 3a1a651d92f7533b974ad74e69956fb815bd9fbe
  scm: git

- name: infra-role-dist-validators
  src: git@github.com:status-im/infra-role-dist-validators.git
  version: 1ec52b38e36cd1af939317ea51bbd74984986725
  scm: git

- name: infra-role-rocketpool-smart-node
  src: git@github.com:status-im/infra-role-rocketpool-smart-node.git
  version: b1f9b4a02c39bd131958234ae79c73ea379235c4
  scm: git

- name: infra-role-winsw
  src: git@github.com:status-im/infra-role-winsw.git
  version: 1b633346c0b2c05095c29f1f0a4e4a76d60d1e99
  scm: git

- name: kibana
  src: git@github.com:status-im/infra-role-kibana.git
  version: 6c170c45c8776fcd1f9cef2274488519245cd35b
  scm: git

- name: elasticsearch
  src: git@github.com:status-im/infra-role-elasticsearch.git
  version: 21a90e184941a708fd6c7386ac7ec2f365286f24
  scm: git

- name: elasticsearch-hq
  src: git@github.com:status-im/infra-role-elasticsearch-hq.git
  version: a92df1ac36c9a8e86fabefb54e24fe33d572ce10
  scm: git

- name: elasticsearch-lb
  src: git@github.com:status-im/infra-role-elasticsearch-lb.git
  version: 7a6018c791690f2ed3e07a9d44319846b6e76b6d
  scm: git

- name: systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  version: cf1798b1eb49af97a62675fa865a89919d7e0bd1
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 7b63fb7b5f0c525aa191e1a410fd79f7eab8d11a
  scm: git

- name: infra-role-geth
  src: git@github.com:status-im/infra-role-geth.git
  version: 87b6be842f1cc4f69ac1f064150c9568aebcdb69
  scm: git

- name: infra-role-geth-exporter
  src: git@github.com:status-im/infra-role-geth-exporter.git
  version: 30e6a08e9b2badffbd32472fff640aefef26fd37
  scm: git
