- name: origin-cert
  src: git@github.com:status-im/infra-role-origin-cert.git
  scm: git

- name: infra-role-tinc
  src: git@github.com:status-im/infra-role-tinc.git
  scm: git

- name: infra-role-bootstrap
  src: git@github.com:status-im/infra-role-bootstrap.git
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  scm: git

- name: infra-role-beacon-node
  src: git@github.com:status-im/infra-role-beacon-node.git
  scm: git

- name: eth2-testnet-site
  src: git@github.com:status-im/infra-role-eth2-testnet-site.git
  scm: git
