---
- name: Create user for beacon node builds
  user:
    name: '{{ beacon_node_builds_user }}'
    group: 'adm'
    groups: ['docker']
    shell: '/bin/zsh'

- name: Set disable rebase as merge strategy
  git_config:
    scope: 'global'
    name: 'pull.rebase'
    value: false
  become_user: '{{ beacon_node_builds_user }}'

- name: Configure access to Docker Hub
  docker_login:
    username: '{{ beacon_node_builds_docker_hub_user | mandatory }}'
    password: '{{ beacon_node_builds_docker_hub_token | mandatory }}'
  become_user: '{{ beacon_node_builds_user }}'
