---
- name: Find new and old validators
  include_tasks: read.yml
- name: Verify if validators changed
  include_tasks: check.yml
- name: Copy over validators and secrets
  include_tasks: write.yml
  when: secrets_changed or validators_changed
